"""update_financial_data_schema

Revision ID: 0619f8965ec9
Revises: 1a0a78d7fb61
Create Date: 2025-07-26 12:03:22.532081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0619f8965ec9'
down_revision: Union[str, None] = '1a0a78d7fb61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_data', 'net_income',
                    new_column_name='net_profit')
    op.alter_column('financial_data', 'net_income_margin',
                    new_column_name='net_profit_margin')
    op.alter_column('financial_data', 'net_income_yoy_change',
                    new_column_name='net_profit_yoy_change')

    # If eps_high/eps_low were replaced with a single eps column
    op.alter_column('financial_data', 'eps_high',
                    new_column_name='price_high')
    op.alter_column('financial_data', 'eps_low',
                    new_column_name='price_low')
    op.add_column('financial_data', sa.Column('eps', sa.Float(), nullable=False, server_default='0'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_data', 'net_profit',
                    new_column_name='net_income')
    op.alter_column('financial_data', 'net_profit_margin',
                    new_column_name='net_income_margin')
    op.alter_column('financial_data', 'net_profit_yoy_change',
                    new_column_name='net_income_yoy_change')
    op.alter_column('financial_data', 'price_high',
                    new_column_name='eps_high')
    op.alter_column('financial_data', 'price_low',
                    new_column_name='eps_low')
    op.drop_column('financial_data', 'eps')
   
    # ### end Alembic commands ###
