"""Add revenue_yoy_change to financial_data

Revision ID: 1a0a78d7fb61
Revises: 9f611e0de550
Create Date: 2025-07-23 19:04:07.858009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0a78d7fb61'
down_revision: Union[str, None] = '9f611e0de550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_data', sa.Column('revenue_yoy_change', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('gross_profit_margin', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('gross_profit_yoy_change', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('operating_profit_margin', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('operating_profit_yoy_change', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('net_income_margin', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('net_income_yoy_change', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('free_cash_flow_yoy_change', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('return_on_equity', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('return_on_assets', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('return_on_invested_capital', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('book_value', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('book_value_per_share', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('book_value_yoy_change', sa.Float(), nullable=True))
    op.add_column('financial_data', sa.Column('current_ratio', sa.Float(), nullable=True))
    op.alter_column('financial_data', 'total_assets',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('financial_data', 'shareholders_equity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('financial_data', 'current_assets',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('financial_data', 'current_liabilities',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('financial_data', 'current_liabilities',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('financial_data', 'current_assets',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('financial_data', 'shareholders_equity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('financial_data', 'total_assets',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('financial_data', 'current_ratio')
    op.drop_column('financial_data', 'book_value_yoy_change')
    op.drop_column('financial_data', 'book_value_per_share')
    op.drop_column('financial_data', 'book_value')
    op.drop_column('financial_data', 'return_on_invested_capital')
    op.drop_column('financial_data', 'return_on_assets')
    op.drop_column('financial_data', 'return_on_equity')
    op.drop_column('financial_data', 'free_cash_flow_yoy_change')
    op.drop_column('financial_data', 'net_income_yoy_change')
    op.drop_column('financial_data', 'net_income_margin')
    op.drop_column('financial_data', 'operating_profit_yoy_change')
    op.drop_column('financial_data', 'operating_profit_margin')
    op.drop_column('financial_data', 'gross_profit_yoy_change')
    op.drop_column('financial_data', 'gross_profit_margin')
    op.drop_column('financial_data', 'revenue_yoy_change')
    # ### end Alembic commands ###
