"""add first_name, last_name in user table

Revision ID: d27286f1a0d2
Revises: 4d0ed1eb2531
Create Date: 2025-07-20 08:29:27.690772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd27286f1a0d2'
down_revision: Union[str, None] = '4d0ed1eb2531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
